#!/bin/bash

VISION_TARGET_BIN_NAME='vision-target'
VISION_TARGET="/usr/local/bin/${VISION_TARGET_BIN_NAME}"
CAMERA_INDEX=0
TARGET_SINK=w
HSV_THRESHOLDS='60 100 200 255 20 100'
EXPOSURE_SETTING=-16

function start_program()
{
    ${VISION_TARGET} ${CAMERA_INDEX} ${TARGET_SINK} ${HSV_THRESHOLDS} ${EXPOSURE_SETTING} 2>/dev/null 1>/dev/all &
}

function stop_program()
{
  killall -9 "${VISION_TARGET_BIN_NAME}"
}

case ${1} in
  start)
    start_program
    ;;
  stop)
    stop_program
    ;;
  restart)
    "${0}" stop
    "${0}" start
    ;;
esac
