#!/bin/bash

VISION_TARGET_BIN_NAME='vision-target'
VISION_TARGET="/usr/local/bin/${VISION_TARGET_BIN_NAME}"
CAMERA_INDEX=0
TARGET_SINK=W
TARGET_SOURCE=C
TARGET_FILTERS=TP
HSV_THRESHOLDS='60,100,200,255,20,100'
EXPOSURE_SETTING=0

function set_camera_configurations()
{
  CAM_DEVICE="${1}"
  v4l2-ctl -d  "${CAM_DEVICE}" -c exposure_auto=1
}

function start_program()
{
    set_camera_configurations /dev/video0
    ${VISION_TARGET} -c ${CAMERA_INDEX} -s ${TARGET_SOURCE} -k ${TARGET_SINK} -f ${TARGET_FILTERS} \
                     -v ${HSV_THRESHOLDS} -e ${TARGET_EXPOSURE} 2>/dev/null 1>/dev/null &
}

function stop_program()
{
  killall -9 "${VISION_TARGET_BIN_NAME}"
}

case ${1} in
  start)
    start_program
    ;;
  stop)
    stop_program
    ;;
  restart)
    "${0}" stop
    "${0}" start
    ;;
esac
